# Generated by Django 3.2.6 on 2021-09-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Ambiente', models.IntegerField()),
                ('Descripcion_Infraestructura', models.CharField(max_length=50)),
                ('Capacidad', models.IntegerField()),
                ('TipoDeAmbiente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo_Perfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Perfiles', models.IntegerField()),
                ('Perfil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo_TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_TipoDocumento', models.IntegerField()),
                ('TipoDocumento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Competencia', models.IntegerField()),
                ('Horas', models.IntegerField()),
                ('Competencia', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Resultado', models.IntegerField()),
                ('Resultado', models.CharField(max_length=50)),
                ('Abordado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Programas_de_Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ProgramaFormacion', models.IntegerField()),
                ('TipoDePrograma', models.CharField(max_length=50)),
                ('FechaInicioEtapaLectiva', models.DateField()),
                ('FechaFinEtapaLectiva', models.DateField()),
                ('CantidadAprendices', models.IntegerField()),
                ('id_Competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.competencias')),
            ],
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Instructor', models.IntegerField()),
                ('NumeroDocumento', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('id_Perfiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.catalogo_perfiles')),
                ('id_TipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.catalogo_tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Horario_Instructor', models.IntegerField()),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('Evento', models.CharField(max_length=50)),
                ('LugarFormacion', models.CharField(max_length=40)),
                ('id_Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.instructores')),
            ],
        ),
        migrations.CreateModel(
            name='Diseno_Curricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Diseno_Curricular', models.IntegerField()),
                ('eventoDi', models.CharField(max_length=180)),
                ('id_Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.instructores')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Coordinacion', models.IntegerField()),
                ('Coordinacion', models.CharField(max_length=30)),
                ('id_Ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.ambientes')),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Contratacion', models.IntegerField()),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('Supervisora', models.CharField(max_length=100)),
                ('id_Coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.coordinaciones')),
                ('id_Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.instructores')),
            ],
        ),
        migrations.AddField(
            model_name='competencias',
            name='id_Resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.resultados'),
        ),
    ]
