# Generated by Django 3.2.6 on 2021-09-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencias',
            name='id_Resultado',
        ),
        migrations.RemoveField(
            model_name='coordinaciones',
            name='id_Ambiente',
        ),
        migrations.RemoveField(
            model_name='diseno_curricular',
            name='id_Instructor',
        ),
        migrations.RemoveField(
            model_name='horario_instructor',
            name='id_Instructor',
        ),
        migrations.RemoveField(
            model_name='programas_de_formacion',
            name='id_Competencia',
        ),
        migrations.RemoveField(
            model_name='catalogo_perfiles',
            name='id_Perfiles',
        ),
        migrations.RemoveField(
            model_name='catalogo_tipodocumento',
            name='id_TipoDocumento',
        ),
        migrations.RemoveField(
            model_name='contratacion',
            name='id_Contratacion',
        ),
        migrations.RemoveField(
            model_name='contratacion',
            name='id_Coordinacion',
        ),
        migrations.RemoveField(
            model_name='instructores',
            name='id_Instructor',
        ),
        migrations.DeleteModel(
            name='Ambientes',
        ),
        migrations.DeleteModel(
            name='Competencias',
        ),
        migrations.DeleteModel(
            name='Coordinaciones',
        ),
        migrations.DeleteModel(
            name='Diseno_Curricular',
        ),
        migrations.DeleteModel(
            name='Horario_Instructor',
        ),
        migrations.DeleteModel(
            name='Programas_de_Formacion',
        ),
        migrations.DeleteModel(
            name='Resultados',
        ),
    ]
