# Generated by Django 3.2.6 on 2021-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0003_auto_20210928_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacion',
            name='Fecha_Fin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contratacion',
            name='Fecha_Inicio',
            field=models.CharField(max_length=20),
        ),
    ]
