# Generated by Django 3.2.3 on 2021-11-04 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0004_auto_20210928_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario_Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('Evento', models.TextField(help_text='Ingrese el evento: Competencia + Resultado + activiad de proyecto', max_length=500)),
                ('LugarFormacion', models.CharField(max_length=50)),
                ('id_Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.instructores')),
            ],
        ),
    ]
