# Generated by Django 3.2.3 on 2021-11-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0006_auto_20211109_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='horasMensualFormacion',
            field=models.IntegerField(null=True),
        ),
    ]
