# Generated by Django 3.2.3 on 2021-11-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0007_contratacion_horasmensualformacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.TextField(max_length=300)),
                ('Horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramasFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProgramaFormacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FichasCaracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ficha', models.CharField(max_length=10)),
                ('FechaInicioEtapaLectiva', models.DateField()),
                ('FechaFinEtapaLectiva', models.DateField()),
                ('CantidadAprendices', models.IntegerField()),
                ('Jornada', models.CharField(max_length=30)),
                ('ProgramasFormacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.programasformacion')),
            ],
        ),
    ]
