# Generated by Django 3.2.3 on 2021-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0008_competencias_fichascaracterizacion_programasformacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencias',
            name='ProgramasFormaciones',
            field=models.ManyToManyField(to='asistenteHorarios.ProgramasFormacion'),
        ),
        migrations.AlterField(
            model_name='competencias',
            name='competencia',
            field=models.TextField(max_length=400),
        ),
    ]
