# Generated by Django 3.2.3 on 2021-11-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0009_auto_20211118_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resultado', models.TextField(max_length=300)),
                ('Abordado', models.BooleanField()),
                ('Competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.competencias')),
            ],
        ),
    ]
