# Generated by Django 3.2.3 on 2021-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0011_ordenrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencias',
            name='codigoCompetencia',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
