# Generated by Django 3.2.3 on 2021-11-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0013_resultados_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultados',
            name='Ficha',
        ),
        migrations.AddField(
            model_name='resultados',
            name='Ficha',
            field=models.ManyToManyField(to='asistenteHorarios.FichasCaracterizacion'),
        ),
    ]
