# Generated by Django 3.2.3 on 2021-11-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0014_auto_20211123_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultados',
            name='Ficha',
        ),
        migrations.AddField(
            model_name='fichascaracterizacion',
            name='Avance',
            field=models.ManyToManyField(to='asistenteHorarios.Resultados'),
        ),
    ]
