# Generated by Django 3.2.3 on 2021-12-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0016_auto_20211214_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxiliar',
            name='ficha',
        ),
    ]
