# Generated by Django 3.2.3 on 2021-12-15 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0017_remove_auxiliar_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenrap',
            name='Ficha',
        ),
        migrations.AddField(
            model_name='ordenrap',
            name='Ficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistenteHorarios.fichascaracterizacion'),
        ),
        migrations.AlterField(
            model_name='ordenrap',
            name='Resultado',
            field=models.ManyToManyField(to='asistenteHorarios.Resultados'),
        ),
        migrations.DeleteModel(
            name='auxiliar',
        ),
    ]
