# Generated by Django 3.2.3 on 2021-12-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistenteHorarios', '0019_auto_20211214_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenrap',
            name='Ficha',
        ),
    ]
